// This file is generated by LanguageTagsCreate

namespace ptr727.LanguageTags;

public partial class Iso6392Data
{
    public static Iso6392Data Create() =>
        new()
        {
            RecordList =
            [
                new()
                {
                    Part2B = "aar",
                    Part1 = "aa",
                    RefName = "Afar",
                },
                new()
                {
                    Part2B = "abk",
                    Part1 = "ab",
                    RefName = "Abkhazian",
                },
                new() { Part2B = "ace", RefName = "Achinese" },
                new() { Part2B = "ach", RefName = "Acoli" },
                new() { Part2B = "ada", RefName = "Adangme" },
                new() { Part2B = "ady", RefName = "Adyghe; Adygei" },
                new() { Part2B = "afa", RefName = "Afro-Asiatic languages" },
                new() { Part2B = "afh", RefName = "Afrihili" },
                new()
                {
                    Part2B = "afr",
                    Part1 = "af",
                    RefName = "Afrikaans",
                },
                new() { Part2B = "ain", RefName = "Ainu" },
                new()
                {
                    Part2B = "aka",
                    Part1 = "ak",
                    RefName = "Akan",
                },
                new() { Part2B = "akk", RefName = "Akkadian" },
                new()
                {
                    Part2B = "alb",
                    Part2T = "sqi",
                    Part1 = "sq",
                    RefName = "Albanian",
                },
                new() { Part2B = "ale", RefName = "Aleut" },
                new() { Part2B = "alg", RefName = "Algonquian languages" },
                new() { Part2B = "alt", RefName = "Southern Altai" },
                new()
                {
                    Part2B = "amh",
                    Part1 = "am",
                    RefName = "Amharic",
                },
                new() { Part2B = "ang", RefName = "English, Old (ca.450-1100)" },
                new() { Part2B = "anp", RefName = "Angika" },
                new() { Part2B = "apa", RefName = "Apache languages" },
                new()
                {
                    Part2B = "ara",
                    Part1 = "ar",
                    RefName = "Arabic",
                },
                new()
                {
                    Part2B = "arc",
                    RefName = "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)",
                },
                new()
                {
                    Part2B = "arg",
                    Part1 = "an",
                    RefName = "Aragonese",
                },
                new()
                {
                    Part2B = "arm",
                    Part2T = "hye",
                    Part1 = "hy",
                    RefName = "Armenian",
                },
                new() { Part2B = "arn", RefName = "Mapudungun; Mapuche" },
                new() { Part2B = "arp", RefName = "Arapaho" },
                new() { Part2B = "art", RefName = "Artificial languages" },
                new() { Part2B = "arw", RefName = "Arawak" },
                new()
                {
                    Part2B = "asm",
                    Part1 = "as",
                    RefName = "Assamese",
                },
                new() { Part2B = "ast", RefName = "Asturian; Bable; Leonese; Asturleonese" },
                new() { Part2B = "ath", RefName = "Athapascan languages" },
                new() { Part2B = "aus", RefName = "Australian languages" },
                new()
                {
                    Part2B = "ava",
                    Part1 = "av",
                    RefName = "Avaric",
                },
                new()
                {
                    Part2B = "ave",
                    Part1 = "ae",
                    RefName = "Avestan",
                },
                new() { Part2B = "awa", RefName = "Awadhi" },
                new()
                {
                    Part2B = "aym",
                    Part1 = "ay",
                    RefName = "Aymara",
                },
                new()
                {
                    Part2B = "aze",
                    Part1 = "az",
                    RefName = "Azerbaijani",
                },
                new() { Part2B = "bad", RefName = "Banda languages" },
                new() { Part2B = "bai", RefName = "Bamileke languages" },
                new()
                {
                    Part2B = "bak",
                    Part1 = "ba",
                    RefName = "Bashkir",
                },
                new() { Part2B = "bal", RefName = "Baluchi" },
                new()
                {
                    Part2B = "bam",
                    Part1 = "bm",
                    RefName = "Bambara",
                },
                new() { Part2B = "ban", RefName = "Balinese" },
                new()
                {
                    Part2B = "baq",
                    Part2T = "eus",
                    Part1 = "eu",
                    RefName = "Basque",
                },
                new() { Part2B = "bas", RefName = "Basa" },
                new() { Part2B = "bat", RefName = "Baltic languages" },
                new() { Part2B = "bej", RefName = "Beja; Bedawiyet" },
                new()
                {
                    Part2B = "bel",
                    Part1 = "be",
                    RefName = "Belarusian",
                },
                new() { Part2B = "bem", RefName = "Bemba" },
                new()
                {
                    Part2B = "ben",
                    Part1 = "bn",
                    RefName = "Bengali",
                },
                new() { Part2B = "ber", RefName = "Berber languages" },
                new() { Part2B = "bho", RefName = "Bhojpuri" },
                new() { Part2B = "bih", RefName = "Bihari languages" },
                new() { Part2B = "bik", RefName = "Bikol" },
                new() { Part2B = "bin", RefName = "Bini; Edo" },
                new()
                {
                    Part2B = "bis",
                    Part1 = "bi",
                    RefName = "Bislama",
                },
                new() { Part2B = "bla", RefName = "Siksika" },
                new() { Part2B = "bnt", RefName = "Bantu languages" },
                new()
                {
                    Part2B = "bos",
                    Part1 = "bs",
                    RefName = "Bosnian",
                },
                new() { Part2B = "bra", RefName = "Braj" },
                new()
                {
                    Part2B = "bre",
                    Part1 = "br",
                    RefName = "Breton",
                },
                new() { Part2B = "btk", RefName = "Batak languages" },
                new() { Part2B = "bua", RefName = "Buriat" },
                new() { Part2B = "bug", RefName = "Buginese" },
                new()
                {
                    Part2B = "bul",
                    Part1 = "bg",
                    RefName = "Bulgarian",
                },
                new()
                {
                    Part2B = "bur",
                    Part2T = "mya",
                    Part1 = "my",
                    RefName = "Burmese",
                },
                new() { Part2B = "byn", RefName = "Blin; Bilin" },
                new() { Part2B = "cad", RefName = "Caddo" },
                new() { Part2B = "cai", RefName = "Central American Indian languages" },
                new() { Part2B = "car", RefName = "Galibi Carib" },
                new()
                {
                    Part2B = "cat",
                    Part1 = "ca",
                    RefName = "Catalan; Valencian",
                },
                new() { Part2B = "cau", RefName = "Caucasian languages" },
                new() { Part2B = "ceb", RefName = "Cebuano" },
                new() { Part2B = "cel", RefName = "Celtic languages" },
                new()
                {
                    Part2B = "cha",
                    Part1 = "ch",
                    RefName = "Chamorro",
                },
                new() { Part2B = "chb", RefName = "Chibcha" },
                new()
                {
                    Part2B = "che",
                    Part1 = "ce",
                    RefName = "Chechen",
                },
                new() { Part2B = "chg", RefName = "Chagatai" },
                new()
                {
                    Part2B = "chi",
                    Part2T = "zho",
                    Part1 = "zh",
                    RefName = "Chinese",
                },
                new() { Part2B = "chk", RefName = "Chuukese" },
                new() { Part2B = "chm", RefName = "Mari" },
                new() { Part2B = "chn", RefName = "Chinook jargon" },
                new() { Part2B = "cho", RefName = "Choctaw" },
                new() { Part2B = "chp", RefName = "Chipewyan; Dene Suline" },
                new() { Part2B = "chr", RefName = "Cherokee" },
                new()
                {
                    Part2B = "chu",
                    Part1 = "cu",
                    RefName =
                        "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
                },
                new()
                {
                    Part2B = "chv",
                    Part1 = "cv",
                    RefName = "Chuvash",
                },
                new() { Part2B = "chy", RefName = "Cheyenne" },
                new() { Part2B = "cmc", RefName = "Chamic languages" },
                new() { Part2B = "cnr", RefName = "Montenegrin" },
                new() { Part2B = "cop", RefName = "Coptic" },
                new()
                {
                    Part2B = "cor",
                    Part1 = "kw",
                    RefName = "Cornish",
                },
                new()
                {
                    Part2B = "cos",
                    Part1 = "co",
                    RefName = "Corsican",
                },
                new() { Part2B = "cpe", RefName = "Creoles and pidgins, English based" },
                new() { Part2B = "cpf", RefName = "Creoles and pidgins, French-based" },
                new() { Part2B = "cpp", RefName = "Creoles and pidgins, Portuguese-based" },
                new()
                {
                    Part2B = "cre",
                    Part1 = "cr",
                    RefName = "Cree",
                },
                new() { Part2B = "crh", RefName = "Crimean Tatar; Crimean Turkish" },
                new() { Part2B = "crp", RefName = "Creoles and pidgins" },
                new() { Part2B = "csb", RefName = "Kashubian" },
                new() { Part2B = "cus", RefName = "Cushitic languages" },
                new()
                {
                    Part2B = "cze",
                    Part2T = "ces",
                    Part1 = "cs",
                    RefName = "Czech",
                },
                new() { Part2B = "dak", RefName = "Dakota" },
                new()
                {
                    Part2B = "dan",
                    Part1 = "da",
                    RefName = "Danish",
                },
                new() { Part2B = "dar", RefName = "Dargwa" },
                new() { Part2B = "day", RefName = "Land Dayak languages" },
                new() { Part2B = "del", RefName = "Delaware" },
                new() { Part2B = "den", RefName = "Slave (Athapascan)" },
                new() { Part2B = "dgr", RefName = "Tlicho; Dogrib" },
                new() { Part2B = "din", RefName = "Dinka" },
                new()
                {
                    Part2B = "div",
                    Part1 = "dv",
                    RefName = "Divehi; Dhivehi; Maldivian",
                },
                new() { Part2B = "doi", RefName = "Dogri" },
                new() { Part2B = "dra", RefName = "Dravidian languages" },
                new() { Part2B = "dsb", RefName = "Lower Sorbian" },
                new() { Part2B = "dua", RefName = "Duala" },
                new() { Part2B = "dum", RefName = "Dutch, Middle (ca.1050-1350)" },
                new()
                {
                    Part2B = "dut",
                    Part2T = "nld",
                    Part1 = "nl",
                    RefName = "Dutch; Flemish",
                },
                new() { Part2B = "dyu", RefName = "Dyula" },
                new()
                {
                    Part2B = "dzo",
                    Part1 = "dz",
                    RefName = "Dzongkha",
                },
                new() { Part2B = "efi", RefName = "Efik" },
                new() { Part2B = "egy", RefName = "Egyptian (Ancient)" },
                new() { Part2B = "eka", RefName = "Ekajuk" },
                new() { Part2B = "elx", RefName = "Elamite" },
                new()
                {
                    Part2B = "eng",
                    Part1 = "en",
                    RefName = "English",
                },
                new() { Part2B = "enm", RefName = "English, Middle (1100-1500)" },
                new()
                {
                    Part2B = "epo",
                    Part1 = "eo",
                    RefName = "Esperanto",
                },
                new()
                {
                    Part2B = "est",
                    Part1 = "et",
                    RefName = "Estonian",
                },
                new()
                {
                    Part2B = "ewe",
                    Part1 = "ee",
                    RefName = "Ewe",
                },
                new() { Part2B = "ewo", RefName = "Ewondo" },
                new() { Part2B = "fan", RefName = "Fang" },
                new()
                {
                    Part2B = "fao",
                    Part1 = "fo",
                    RefName = "Faroese",
                },
                new() { Part2B = "fat", RefName = "Fanti" },
                new()
                {
                    Part2B = "fij",
                    Part1 = "fj",
                    RefName = "Fijian",
                },
                new() { Part2B = "fil", RefName = "Filipino; Pilipino" },
                new()
                {
                    Part2B = "fin",
                    Part1 = "fi",
                    RefName = "Finnish",
                },
                new() { Part2B = "fiu", RefName = "Finno-Ugrian languages" },
                new() { Part2B = "fon", RefName = "Fon" },
                new()
                {
                    Part2B = "fre",
                    Part2T = "fra",
                    Part1 = "fr",
                    RefName = "French",
                },
                new() { Part2B = "frm", RefName = "French, Middle (ca.1400-1600)" },
                new() { Part2B = "fro", RefName = "French, Old (842-ca.1400)" },
                new() { Part2B = "frr", RefName = "Northern Frisian" },
                new() { Part2B = "frs", RefName = "Eastern Frisian" },
                new()
                {
                    Part2B = "fry",
                    Part1 = "fy",
                    RefName = "Western Frisian",
                },
                new()
                {
                    Part2B = "ful",
                    Part1 = "ff",
                    RefName = "Fulah",
                },
                new() { Part2B = "fur", RefName = "Friulian" },
                new() { Part2B = "gaa", RefName = "Ga" },
                new() { Part2B = "gay", RefName = "Gayo" },
                new() { Part2B = "gba", RefName = "Gbaya" },
                new() { Part2B = "gem", RefName = "Germanic languages" },
                new()
                {
                    Part2B = "geo",
                    Part2T = "kat",
                    Part1 = "ka",
                    RefName = "Georgian",
                },
                new()
                {
                    Part2B = "ger",
                    Part2T = "deu",
                    Part1 = "de",
                    RefName = "German",
                },
                new() { Part2B = "gez", RefName = "Geez" },
                new() { Part2B = "gil", RefName = "Gilbertese" },
                new()
                {
                    Part2B = "gla",
                    Part1 = "gd",
                    RefName = "Gaelic; Scottish Gaelic",
                },
                new()
                {
                    Part2B = "gle",
                    Part1 = "ga",
                    RefName = "Irish",
                },
                new()
                {
                    Part2B = "glg",
                    Part1 = "gl",
                    RefName = "Galician",
                },
                new()
                {
                    Part2B = "glv",
                    Part1 = "gv",
                    RefName = "Manx",
                },
                new() { Part2B = "gmh", RefName = "German, Middle High (ca.1050-1500)" },
                new() { Part2B = "goh", RefName = "German, Old High (ca.750-1050)" },
                new() { Part2B = "gon", RefName = "Gondi" },
                new() { Part2B = "gor", RefName = "Gorontalo" },
                new() { Part2B = "got", RefName = "Gothic" },
                new() { Part2B = "grb", RefName = "Grebo" },
                new() { Part2B = "grc", RefName = "Greek, Ancient (to 1453)" },
                new()
                {
                    Part2B = "gre",
                    Part2T = "ell",
                    Part1 = "el",
                    RefName = "Greek, Modern (1453-)",
                },
                new()
                {
                    Part2B = "grn",
                    Part1 = "gn",
                    RefName = "Guarani",
                },
                new() { Part2B = "gsw", RefName = "Swiss German; Alemannic; Alsatian" },
                new()
                {
                    Part2B = "guj",
                    Part1 = "gu",
                    RefName = "Gujarati",
                },
                new() { Part2B = "gwi", RefName = "Gwich'in" },
                new() { Part2B = "hai", RefName = "Haida" },
                new()
                {
                    Part2B = "hat",
                    Part1 = "ht",
                    RefName = "Haitian; Haitian Creole",
                },
                new()
                {
                    Part2B = "hau",
                    Part1 = "ha",
                    RefName = "Hausa",
                },
                new() { Part2B = "haw", RefName = "Hawaiian" },
                new()
                {
                    Part2B = "heb",
                    Part1 = "he",
                    RefName = "Hebrew",
                },
                new()
                {
                    Part2B = "her",
                    Part1 = "hz",
                    RefName = "Herero",
                },
                new() { Part2B = "hil", RefName = "Hiligaynon" },
                new() { Part2B = "him", RefName = "Himachali languages; Western Pahari languages" },
                new()
                {
                    Part2B = "hin",
                    Part1 = "hi",
                    RefName = "Hindi",
                },
                new() { Part2B = "hit", RefName = "Hittite" },
                new() { Part2B = "hmn", RefName = "Hmong; Mong" },
                new()
                {
                    Part2B = "hmo",
                    Part1 = "ho",
                    RefName = "Hiri Motu",
                },
                new()
                {
                    Part2B = "hrv",
                    Part1 = "hr",
                    RefName = "Croatian",
                },
                new() { Part2B = "hsb", RefName = "Upper Sorbian" },
                new()
                {
                    Part2B = "hun",
                    Part1 = "hu",
                    RefName = "Hungarian",
                },
                new() { Part2B = "hup", RefName = "Hupa" },
                new() { Part2B = "iba", RefName = "Iban" },
                new()
                {
                    Part2B = "ibo",
                    Part1 = "ig",
                    RefName = "Igbo",
                },
                new()
                {
                    Part2B = "ice",
                    Part2T = "isl",
                    Part1 = "is",
                    RefName = "Icelandic",
                },
                new()
                {
                    Part2B = "ido",
                    Part1 = "io",
                    RefName = "Ido",
                },
                new()
                {
                    Part2B = "iii",
                    Part1 = "ii",
                    RefName = "Sichuan Yi; Nuosu",
                },
                new() { Part2B = "ijo", RefName = "Ijo languages" },
                new()
                {
                    Part2B = "iku",
                    Part1 = "iu",
                    RefName = "Inuktitut",
                },
                new()
                {
                    Part2B = "ile",
                    Part1 = "ie",
                    RefName = "Interlingue; Occidental",
                },
                new() { Part2B = "ilo", RefName = "Iloko" },
                new()
                {
                    Part2B = "ina",
                    Part1 = "ia",
                    RefName = "Interlingua (International Auxiliary Language Association)",
                },
                new() { Part2B = "inc", RefName = "Indic languages" },
                new()
                {
                    Part2B = "ind",
                    Part1 = "id",
                    RefName = "Indonesian",
                },
                new() { Part2B = "ine", RefName = "Indo-European languages" },
                new() { Part2B = "inh", RefName = "Ingush" },
                new()
                {
                    Part2B = "ipk",
                    Part1 = "ik",
                    RefName = "Inupiaq",
                },
                new() { Part2B = "ira", RefName = "Iranian languages" },
                new() { Part2B = "iro", RefName = "Iroquoian languages" },
                new()
                {
                    Part2B = "ita",
                    Part1 = "it",
                    RefName = "Italian",
                },
                new()
                {
                    Part2B = "jav",
                    Part1 = "jv",
                    RefName = "Javanese",
                },
                new() { Part2B = "jbo", RefName = "Lojban" },
                new()
                {
                    Part2B = "jpn",
                    Part1 = "ja",
                    RefName = "Japanese",
                },
                new() { Part2B = "jpr", RefName = "Judeo-Persian" },
                new() { Part2B = "jrb", RefName = "Judeo-Arabic" },
                new() { Part2B = "kaa", RefName = "Kara-Kalpak" },
                new() { Part2B = "kab", RefName = "Kabyle" },
                new() { Part2B = "kac", RefName = "Kachin; Jingpho" },
                new()
                {
                    Part2B = "kal",
                    Part1 = "kl",
                    RefName = "Kalaallisut; Greenlandic",
                },
                new() { Part2B = "kam", RefName = "Kamba" },
                new()
                {
                    Part2B = "kan",
                    Part1 = "kn",
                    RefName = "Kannada",
                },
                new() { Part2B = "kar", RefName = "Karen languages" },
                new()
                {
                    Part2B = "kas",
                    Part1 = "ks",
                    RefName = "Kashmiri",
                },
                new()
                {
                    Part2B = "kau",
                    Part1 = "kr",
                    RefName = "Kanuri",
                },
                new() { Part2B = "kaw", RefName = "Kawi" },
                new()
                {
                    Part2B = "kaz",
                    Part1 = "kk",
                    RefName = "Kazakh",
                },
                new() { Part2B = "kbd", RefName = "Kabardian" },
                new() { Part2B = "kha", RefName = "Khasi" },
                new() { Part2B = "khi", RefName = "Khoisan languages" },
                new()
                {
                    Part2B = "khm",
                    Part1 = "km",
                    RefName = "Central Khmer",
                },
                new() { Part2B = "kho", RefName = "Khotanese; Sakan" },
                new()
                {
                    Part2B = "kik",
                    Part1 = "ki",
                    RefName = "Kikuyu; Gikuyu",
                },
                new()
                {
                    Part2B = "kin",
                    Part1 = "rw",
                    RefName = "Kinyarwanda",
                },
                new()
                {
                    Part2B = "kir",
                    Part1 = "ky",
                    RefName = "Kirghiz; Kyrgyz",
                },
                new() { Part2B = "kmb", RefName = "Kimbundu" },
                new() { Part2B = "kok", RefName = "Konkani" },
                new()
                {
                    Part2B = "kom",
                    Part1 = "kv",
                    RefName = "Komi",
                },
                new()
                {
                    Part2B = "kon",
                    Part1 = "kg",
                    RefName = "Kongo",
                },
                new()
                {
                    Part2B = "kor",
                    Part1 = "ko",
                    RefName = "Korean",
                },
                new() { Part2B = "kos", RefName = "Kosraean" },
                new() { Part2B = "kpe", RefName = "Kpelle" },
                new() { Part2B = "krc", RefName = "Karachay-Balkar" },
                new() { Part2B = "krl", RefName = "Karelian" },
                new() { Part2B = "kro", RefName = "Kru languages" },
                new() { Part2B = "kru", RefName = "Kurukh" },
                new()
                {
                    Part2B = "kua",
                    Part1 = "kj",
                    RefName = "Kuanyama; Kwanyama",
                },
                new() { Part2B = "kum", RefName = "Kumyk" },
                new()
                {
                    Part2B = "kur",
                    Part1 = "ku",
                    RefName = "Kurdish",
                },
                new() { Part2B = "kut", RefName = "Kutenai" },
                new() { Part2B = "lad", RefName = "Ladino" },
                new() { Part2B = "lah", RefName = "Lahnda" },
                new() { Part2B = "lam", RefName = "Lamba" },
                new()
                {
                    Part2B = "lao",
                    Part1 = "lo",
                    RefName = "Lao",
                },
                new()
                {
                    Part2B = "lat",
                    Part1 = "la",
                    RefName = "Latin",
                },
                new()
                {
                    Part2B = "lav",
                    Part1 = "lv",
                    RefName = "Latvian",
                },
                new() { Part2B = "lez", RefName = "Lezghian" },
                new()
                {
                    Part2B = "lim",
                    Part1 = "li",
                    RefName = "Limburgan; Limburger; Limburgish",
                },
                new()
                {
                    Part2B = "lin",
                    Part1 = "ln",
                    RefName = "Lingala",
                },
                new()
                {
                    Part2B = "lit",
                    Part1 = "lt",
                    RefName = "Lithuanian",
                },
                new() { Part2B = "lol", RefName = "Mongo" },
                new() { Part2B = "loz", RefName = "Lozi" },
                new()
                {
                    Part2B = "ltz",
                    Part1 = "lb",
                    RefName = "Luxembourgish; Letzeburgesch",
                },
                new() { Part2B = "lua", RefName = "Luba-Lulua" },
                new()
                {
                    Part2B = "lub",
                    Part1 = "lu",
                    RefName = "Luba-Katanga",
                },
                new()
                {
                    Part2B = "lug",
                    Part1 = "lg",
                    RefName = "Ganda",
                },
                new() { Part2B = "lui", RefName = "Luiseno" },
                new() { Part2B = "lun", RefName = "Lunda" },
                new() { Part2B = "luo", RefName = "Luo (Kenya and Tanzania)" },
                new() { Part2B = "lus", RefName = "Lushai" },
                new()
                {
                    Part2B = "mac",
                    Part2T = "mkd",
                    Part1 = "mk",
                    RefName = "Macedonian",
                },
                new() { Part2B = "mad", RefName = "Madurese" },
                new() { Part2B = "mag", RefName = "Magahi" },
                new()
                {
                    Part2B = "mah",
                    Part1 = "mh",
                    RefName = "Marshallese",
                },
                new() { Part2B = "mai", RefName = "Maithili" },
                new() { Part2B = "mak", RefName = "Makasar" },
                new()
                {
                    Part2B = "mal",
                    Part1 = "ml",
                    RefName = "Malayalam",
                },
                new() { Part2B = "man", RefName = "Mandingo" },
                new()
                {
                    Part2B = "mao",
                    Part2T = "mri",
                    Part1 = "mi",
                    RefName = "Maori",
                },
                new() { Part2B = "map", RefName = "Austronesian languages" },
                new()
                {
                    Part2B = "mar",
                    Part1 = "mr",
                    RefName = "Marathi",
                },
                new() { Part2B = "mas", RefName = "Masai" },
                new()
                {
                    Part2B = "may",
                    Part2T = "msa",
                    Part1 = "ms",
                    RefName = "Malay",
                },
                new() { Part2B = "mdf", RefName = "Moksha" },
                new() { Part2B = "mdr", RefName = "Mandar" },
                new() { Part2B = "men", RefName = "Mende" },
                new() { Part2B = "mga", RefName = "Irish, Middle (900-1200)" },
                new() { Part2B = "mic", RefName = "Mi'kmaq; Micmac" },
                new() { Part2B = "min", RefName = "Minangkabau" },
                new() { Part2B = "mis", RefName = "Uncoded languages" },
                new() { Part2B = "mkh", RefName = "Mon-Khmer languages" },
                new()
                {
                    Part2B = "mlg",
                    Part1 = "mg",
                    RefName = "Malagasy",
                },
                new()
                {
                    Part2B = "mlt",
                    Part1 = "mt",
                    RefName = "Maltese",
                },
                new() { Part2B = "mnc", RefName = "Manchu" },
                new() { Part2B = "mni", RefName = "Manipuri" },
                new() { Part2B = "mno", RefName = "Manobo languages" },
                new() { Part2B = "moh", RefName = "Mohawk" },
                new()
                {
                    Part2B = "mon",
                    Part1 = "mn",
                    RefName = "Mongolian",
                },
                new() { Part2B = "mos", RefName = "Mossi" },
                new() { Part2B = "mul", RefName = "Multiple languages" },
                new() { Part2B = "mun", RefName = "Munda languages" },
                new() { Part2B = "mus", RefName = "Creek" },
                new() { Part2B = "mwl", RefName = "Mirandese" },
                new() { Part2B = "mwr", RefName = "Marwari" },
                new() { Part2B = "myn", RefName = "Mayan languages" },
                new() { Part2B = "myv", RefName = "Erzya" },
                new() { Part2B = "nah", RefName = "Nahuatl languages" },
                new() { Part2B = "nai", RefName = "North American Indian languages" },
                new() { Part2B = "nap", RefName = "Neapolitan" },
                new()
                {
                    Part2B = "nau",
                    Part1 = "na",
                    RefName = "Nauru",
                },
                new()
                {
                    Part2B = "nav",
                    Part1 = "nv",
                    RefName = "Navajo; Navaho",
                },
                new()
                {
                    Part2B = "nbl",
                    Part1 = "nr",
                    RefName = "Ndebele, South; South Ndebele",
                },
                new()
                {
                    Part2B = "nde",
                    Part1 = "nd",
                    RefName = "Ndebele, North; North Ndebele",
                },
                new()
                {
                    Part2B = "ndo",
                    Part1 = "ng",
                    RefName = "Ndonga",
                },
                new()
                {
                    Part2B = "nds",
                    RefName = "Low German; Low Saxon; German, Low; Saxon, Low",
                },
                new()
                {
                    Part2B = "nep",
                    Part1 = "ne",
                    RefName = "Nepali",
                },
                new() { Part2B = "new", RefName = "Nepal Bhasa; Newari" },
                new() { Part2B = "nia", RefName = "Nias" },
                new() { Part2B = "nic", RefName = "Niger-Kordofanian languages" },
                new() { Part2B = "niu", RefName = "Niuean" },
                new()
                {
                    Part2B = "nno",
                    Part1 = "nn",
                    RefName = "Norwegian Nynorsk; Nynorsk, Norwegian",
                },
                new()
                {
                    Part2B = "nob",
                    Part1 = "nb",
                    RefName = "Bokmål, Norwegian; Norwegian Bokmål",
                },
                new() { Part2B = "nog", RefName = "Nogai" },
                new() { Part2B = "non", RefName = "Norse, Old" },
                new()
                {
                    Part2B = "nor",
                    Part1 = "no",
                    RefName = "Norwegian",
                },
                new() { Part2B = "nqo", RefName = "N'Ko" },
                new() { Part2B = "nso", RefName = "Pedi; Sepedi; Northern Sotho" },
                new() { Part2B = "nub", RefName = "Nubian languages" },
                new()
                {
                    Part2B = "nwc",
                    RefName = "Classical Newari; Old Newari; Classical Nepal Bhasa",
                },
                new()
                {
                    Part2B = "nya",
                    Part1 = "ny",
                    RefName = "Chichewa; Chewa; Nyanja",
                },
                new() { Part2B = "nym", RefName = "Nyamwezi" },
                new() { Part2B = "nyn", RefName = "Nyankole" },
                new() { Part2B = "nyo", RefName = "Nyoro" },
                new() { Part2B = "nzi", RefName = "Nzima" },
                new()
                {
                    Part2B = "oci",
                    Part1 = "oc",
                    RefName = "Occitan (post 1500)",
                },
                new()
                {
                    Part2B = "oji",
                    Part1 = "oj",
                    RefName = "Ojibwa",
                },
                new()
                {
                    Part2B = "ori",
                    Part1 = "or",
                    RefName = "Oriya",
                },
                new()
                {
                    Part2B = "orm",
                    Part1 = "om",
                    RefName = "Oromo",
                },
                new() { Part2B = "osa", RefName = "Osage" },
                new()
                {
                    Part2B = "oss",
                    Part1 = "os",
                    RefName = "Ossetian; Ossetic",
                },
                new() { Part2B = "ota", RefName = "Turkish, Ottoman (1500-1928)" },
                new() { Part2B = "oto", RefName = "Otomian languages" },
                new() { Part2B = "paa", RefName = "Papuan languages" },
                new() { Part2B = "pag", RefName = "Pangasinan" },
                new() { Part2B = "pal", RefName = "Pahlavi" },
                new() { Part2B = "pam", RefName = "Pampanga; Kapampangan" },
                new()
                {
                    Part2B = "pan",
                    Part1 = "pa",
                    RefName = "Panjabi; Punjabi",
                },
                new() { Part2B = "pap", RefName = "Papiamento" },
                new() { Part2B = "pau", RefName = "Palauan" },
                new() { Part2B = "peo", RefName = "Persian, Old (ca.600-400 B.C.)" },
                new()
                {
                    Part2B = "per",
                    Part2T = "fas",
                    Part1 = "fa",
                    RefName = "Persian",
                },
                new() { Part2B = "phi", RefName = "Philippine languages" },
                new() { Part2B = "phn", RefName = "Phoenician" },
                new()
                {
                    Part2B = "pli",
                    Part1 = "pi",
                    RefName = "Pali",
                },
                new()
                {
                    Part2B = "pol",
                    Part1 = "pl",
                    RefName = "Polish",
                },
                new() { Part2B = "pon", RefName = "Pohnpeian" },
                new()
                {
                    Part2B = "por",
                    Part1 = "pt",
                    RefName = "Portuguese",
                },
                new() { Part2B = "pra", RefName = "Prakrit languages" },
                new()
                {
                    Part2B = "pro",
                    RefName = "Provençal, Old (to 1500); Occitan, Old (to 1500)",
                },
                new()
                {
                    Part2B = "pus",
                    Part1 = "ps",
                    RefName = "Pushto; Pashto",
                },
                new() { Part2B = "qaa-qtz", RefName = "Reserved for local use" },
                new()
                {
                    Part2B = "que",
                    Part1 = "qu",
                    RefName = "Quechua",
                },
                new() { Part2B = "raj", RefName = "Rajasthani" },
                new() { Part2B = "rap", RefName = "Rapanui" },
                new() { Part2B = "rar", RefName = "Rarotongan; Cook Islands Maori" },
                new() { Part2B = "roa", RefName = "Romance languages" },
                new()
                {
                    Part2B = "roh",
                    Part1 = "rm",
                    RefName = "Romansh",
                },
                new() { Part2B = "rom", RefName = "Romany" },
                new()
                {
                    Part2B = "rum",
                    Part2T = "ron",
                    Part1 = "ro",
                    RefName = "Romanian; Moldavian; Moldovan",
                },
                new()
                {
                    Part2B = "run",
                    Part1 = "rn",
                    RefName = "Rundi",
                },
                new() { Part2B = "rup", RefName = "Aromanian; Arumanian; Macedo-Romanian" },
                new()
                {
                    Part2B = "rus",
                    Part1 = "ru",
                    RefName = "Russian",
                },
                new() { Part2B = "sad", RefName = "Sandawe" },
                new()
                {
                    Part2B = "sag",
                    Part1 = "sg",
                    RefName = "Sango",
                },
                new() { Part2B = "sah", RefName = "Yakut" },
                new() { Part2B = "sai", RefName = "South American Indian languages" },
                new() { Part2B = "sal", RefName = "Salishan languages" },
                new() { Part2B = "sam", RefName = "Samaritan Aramaic" },
                new()
                {
                    Part2B = "san",
                    Part1 = "sa",
                    RefName = "Sanskrit",
                },
                new() { Part2B = "sas", RefName = "Sasak" },
                new() { Part2B = "sat", RefName = "Santali" },
                new() { Part2B = "scn", RefName = "Sicilian" },
                new() { Part2B = "sco", RefName = "Scots" },
                new() { Part2B = "sel", RefName = "Selkup" },
                new() { Part2B = "sem", RefName = "Semitic languages" },
                new() { Part2B = "sga", RefName = "Irish, Old (to 900)" },
                new() { Part2B = "sgn", RefName = "Sign Languages" },
                new() { Part2B = "shn", RefName = "Shan" },
                new() { Part2B = "sid", RefName = "Sidamo" },
                new()
                {
                    Part2B = "sin",
                    Part1 = "si",
                    RefName = "Sinhala; Sinhalese",
                },
                new() { Part2B = "sio", RefName = "Siouan languages" },
                new() { Part2B = "sit", RefName = "Sino-Tibetan languages" },
                new() { Part2B = "sla", RefName = "Slavic languages" },
                new()
                {
                    Part2B = "slo",
                    Part2T = "slk",
                    Part1 = "sk",
                    RefName = "Slovak",
                },
                new()
                {
                    Part2B = "slv",
                    Part1 = "sl",
                    RefName = "Slovenian",
                },
                new() { Part2B = "sma", RefName = "Southern Sami" },
                new()
                {
                    Part2B = "sme",
                    Part1 = "se",
                    RefName = "Northern Sami",
                },
                new() { Part2B = "smi", RefName = "Sami languages" },
                new() { Part2B = "smj", RefName = "Lule Sami" },
                new() { Part2B = "smn", RefName = "Inari Sami" },
                new()
                {
                    Part2B = "smo",
                    Part1 = "sm",
                    RefName = "Samoan",
                },
                new() { Part2B = "sms", RefName = "Skolt Sami" },
                new()
                {
                    Part2B = "sna",
                    Part1 = "sn",
                    RefName = "Shona",
                },
                new()
                {
                    Part2B = "snd",
                    Part1 = "sd",
                    RefName = "Sindhi",
                },
                new() { Part2B = "snk", RefName = "Soninke" },
                new() { Part2B = "sog", RefName = "Sogdian" },
                new()
                {
                    Part2B = "som",
                    Part1 = "so",
                    RefName = "Somali",
                },
                new() { Part2B = "son", RefName = "Songhai languages" },
                new()
                {
                    Part2B = "sot",
                    Part1 = "st",
                    RefName = "Sotho, Southern",
                },
                new()
                {
                    Part2B = "spa",
                    Part1 = "es",
                    RefName = "Spanish; Castilian",
                },
                new()
                {
                    Part2B = "srd",
                    Part1 = "sc",
                    RefName = "Sardinian",
                },
                new() { Part2B = "srn", RefName = "Sranan Tongo" },
                new()
                {
                    Part2B = "srp",
                    Part1 = "sr",
                    RefName = "Serbian",
                },
                new() { Part2B = "srr", RefName = "Serer" },
                new() { Part2B = "ssa", RefName = "Nilo-Saharan languages" },
                new()
                {
                    Part2B = "ssw",
                    Part1 = "ss",
                    RefName = "Swati",
                },
                new() { Part2B = "suk", RefName = "Sukuma" },
                new()
                {
                    Part2B = "sun",
                    Part1 = "su",
                    RefName = "Sundanese",
                },
                new() { Part2B = "sus", RefName = "Susu" },
                new() { Part2B = "sux", RefName = "Sumerian" },
                new()
                {
                    Part2B = "swa",
                    Part1 = "sw",
                    RefName = "Swahili",
                },
                new()
                {
                    Part2B = "swe",
                    Part1 = "sv",
                    RefName = "Swedish",
                },
                new() { Part2B = "syc", RefName = "Classical Syriac" },
                new() { Part2B = "syr", RefName = "Syriac" },
                new()
                {
                    Part2B = "tah",
                    Part1 = "ty",
                    RefName = "Tahitian",
                },
                new() { Part2B = "tai", RefName = "Tai languages" },
                new()
                {
                    Part2B = "tam",
                    Part1 = "ta",
                    RefName = "Tamil",
                },
                new()
                {
                    Part2B = "tat",
                    Part1 = "tt",
                    RefName = "Tatar",
                },
                new()
                {
                    Part2B = "tel",
                    Part1 = "te",
                    RefName = "Telugu",
                },
                new() { Part2B = "tem", RefName = "Timne" },
                new() { Part2B = "ter", RefName = "Tereno" },
                new() { Part2B = "tet", RefName = "Tetum" },
                new()
                {
                    Part2B = "tgk",
                    Part1 = "tg",
                    RefName = "Tajik",
                },
                new()
                {
                    Part2B = "tgl",
                    Part1 = "tl",
                    RefName = "Tagalog",
                },
                new()
                {
                    Part2B = "tha",
                    Part1 = "th",
                    RefName = "Thai",
                },
                new()
                {
                    Part2B = "tib",
                    Part2T = "bod",
                    Part1 = "bo",
                    RefName = "Tibetan",
                },
                new() { Part2B = "tig", RefName = "Tigre" },
                new()
                {
                    Part2B = "tir",
                    Part1 = "ti",
                    RefName = "Tigrinya",
                },
                new() { Part2B = "tiv", RefName = "Tiv" },
                new() { Part2B = "tkl", RefName = "Tokelau" },
                new() { Part2B = "tlh", RefName = "Klingon; tlhIngan-Hol" },
                new() { Part2B = "tli", RefName = "Tlingit" },
                new() { Part2B = "tmh", RefName = "Tamashek" },
                new() { Part2B = "tog", RefName = "Tonga (Nyasa)" },
                new()
                {
                    Part2B = "ton",
                    Part1 = "to",
                    RefName = "Tonga (Tonga Islands)",
                },
                new() { Part2B = "tpi", RefName = "Tok Pisin" },
                new() { Part2B = "tsi", RefName = "Tsimshian" },
                new()
                {
                    Part2B = "tsn",
                    Part1 = "tn",
                    RefName = "Tswana",
                },
                new()
                {
                    Part2B = "tso",
                    Part1 = "ts",
                    RefName = "Tsonga",
                },
                new()
                {
                    Part2B = "tuk",
                    Part1 = "tk",
                    RefName = "Turkmen",
                },
                new() { Part2B = "tum", RefName = "Tumbuka" },
                new() { Part2B = "tup", RefName = "Tupi languages" },
                new()
                {
                    Part2B = "tur",
                    Part1 = "tr",
                    RefName = "Turkish",
                },
                new() { Part2B = "tut", RefName = "Altaic languages" },
                new() { Part2B = "tvl", RefName = "Tuvalu" },
                new()
                {
                    Part2B = "twi",
                    Part1 = "tw",
                    RefName = "Twi",
                },
                new() { Part2B = "tyv", RefName = "Tuvinian" },
                new() { Part2B = "udm", RefName = "Udmurt" },
                new() { Part2B = "uga", RefName = "Ugaritic" },
                new()
                {
                    Part2B = "uig",
                    Part1 = "ug",
                    RefName = "Uighur; Uyghur",
                },
                new()
                {
                    Part2B = "ukr",
                    Part1 = "uk",
                    RefName = "Ukrainian",
                },
                new() { Part2B = "umb", RefName = "Umbundu" },
                new() { Part2B = "und", RefName = "Undetermined" },
                new()
                {
                    Part2B = "urd",
                    Part1 = "ur",
                    RefName = "Urdu",
                },
                new()
                {
                    Part2B = "uzb",
                    Part1 = "uz",
                    RefName = "Uzbek",
                },
                new() { Part2B = "vai", RefName = "Vai" },
                new()
                {
                    Part2B = "ven",
                    Part1 = "ve",
                    RefName = "Venda",
                },
                new()
                {
                    Part2B = "vie",
                    Part1 = "vi",
                    RefName = "Vietnamese",
                },
                new()
                {
                    Part2B = "vol",
                    Part1 = "vo",
                    RefName = "Volapük",
                },
                new() { Part2B = "vot", RefName = "Votic" },
                new() { Part2B = "wak", RefName = "Wakashan languages" },
                new() { Part2B = "wal", RefName = "Wolaitta; Wolaytta" },
                new() { Part2B = "war", RefName = "Waray" },
                new() { Part2B = "was", RefName = "Washo" },
                new()
                {
                    Part2B = "wel",
                    Part2T = "cym",
                    Part1 = "cy",
                    RefName = "Welsh",
                },
                new() { Part2B = "wen", RefName = "Sorbian languages" },
                new()
                {
                    Part2B = "wln",
                    Part1 = "wa",
                    RefName = "Walloon",
                },
                new()
                {
                    Part2B = "wol",
                    Part1 = "wo",
                    RefName = "Wolof",
                },
                new() { Part2B = "xal", RefName = "Kalmyk; Oirat" },
                new()
                {
                    Part2B = "xho",
                    Part1 = "xh",
                    RefName = "Xhosa",
                },
                new() { Part2B = "yao", RefName = "Yao" },
                new() { Part2B = "yap", RefName = "Yapese" },
                new()
                {
                    Part2B = "yid",
                    Part1 = "yi",
                    RefName = "Yiddish",
                },
                new()
                {
                    Part2B = "yor",
                    Part1 = "yo",
                    RefName = "Yoruba",
                },
                new() { Part2B = "ypk", RefName = "Yupik languages" },
                new() { Part2B = "zap", RefName = "Zapotec" },
                new() { Part2B = "zbl", RefName = "Blissymbols; Blissymbolics; Bliss" },
                new() { Part2B = "zen", RefName = "Zenaga" },
                new() { Part2B = "zgh", RefName = "Standard Moroccan Tamazight" },
                new()
                {
                    Part2B = "zha",
                    Part1 = "za",
                    RefName = "Zhuang; Chuang",
                },
                new() { Part2B = "znd", RefName = "Zande languages" },
                new()
                {
                    Part2B = "zul",
                    Part1 = "zu",
                    RefName = "Zulu",
                },
                new() { Part2B = "zun", RefName = "Zuni" },
                new() { Part2B = "zxx", RefName = "No linguistic content; Not applicable" },
                new()
                {
                    Part2B = "zza",
                    RefName = "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
                },
            ],
        };
}
