name: Test build

on:
  workflow_call:
  workflow_dispatch:

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code style
        run: |
          dotnet tool restore
          dotnet csharpier check --log-level=debug .
          dotnet format style --verify-no-changes --severity=info --verbosity=detailed --exclude-diagnostics=IDE0055

      - name: Run unit tests
        run: dotnet test

      - name: Build
        run: dotnet build
