name: Test PRs

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: Run tests
    uses: ./.github/workflows/test-task.yml
    secrets: inherit
