name: Test PR's

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
