name: Update language data

on:
    workflow_dispatch:
    schedule:
      - cron: '0 2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update:
    name: Update language data
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:

      # https://github.com/marketplace/actions/setup-net-core-sdk
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download language data and generate code
        run: |
          dotnet run --project ./LanguageTagsCreate/LanguageTagsCreate.csproj -- .

      - name: CSharpier format code
        run: |
          dotnet new tool-manifest
          dotnet tool install csharpier
          dotnet csharpier format .
          git status

      # https://github.com/marketplace/actions/create-pull-request
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-languagedata
          title: 'Update language data and generated files'
          body: 'This PR updates the language data files and regenerates the code.'
          commit-message: 'Update language data and generated files'
          delete-branch: true
          labels: 'update-languagedata'
